# 서버 포트 설정
server:
  port: 8080 # 로컬에서 실행될 서버 포트

# 스프링 설정
spring:
  # 데이터베이스 설정 (로컬 MySQL 기준)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heeblings?useSSL=false&allowPublicKeyRetrieval=true
    username: root # 로컬 DB 사용자 이름 (본인 환경에 맞게 수정)
    password: rhflffk # 로컬 DB 비밀번호 (본인 환경에 맞게 수정)

  # JPA(ORM) 설정
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티에 맞춰 테이블 구조 자동 변경 (개발용)
    properties:
      hibernate:
        show_sql: true # 실행되는 SQL 쿼리를 로그로 보여줌
        format_sql: true # SQL 로그를 예쁘게 포맷팅

# JWT 설정
jwt:
  secret: "hello plant care app we are the world" # ❗️반드시 아무도 모르는 긴 문자열로 변경하세요.
  expiration-time: 86400000 # 토큰 유효 기간 (24시간, 밀리초 단위)

# Kakao API 설정
kakao:
  api:
    url: https://kapi.kakao.com
  rest-api-key: "c030c64f8fd6ca291ef21a6ff697c5ac"
  admin-key: "94578d4403639fff17c0bc3e331b2f45"

# firebase 설정
firebase:
  service-account-path: "classpath:my-plant-care-0202-firebase.json"
